apiVersion: v1
kind: Pod
metadata:
  name: bridge-consumer
spec:
  containers:
  - name: tcpdump
    image: corfr/tcpdump
    securityContext:
      privileged: true
    command: ["/bin/sleep", "1234"]
    resources:
      limits:
        bridge.network.kubevirt.io/br0: 1
